// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import path from "path";

// Manually point to .env.local in your root directory
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });


export default defineConfig({
  
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.POSTGRES_PRISMA_URL, 
    directUrl: process.env.POSTGRES_URL_NON_POOLING,
  },
});
